#!/usr/bin/env bash

menu_entries=(
  "SUPER                Open Menu"
  "SUPER + Esc          Power Options"
  "ALT + K              Cheatsheet"
  "SUPER + Q            Open Terminal"
  "SUPER + E            Open Dolphin"
  "SUPER + B            Open Browser (Firefox)"
  "SUPER + T            Open Text Editor (Kate)"
  "ALT + C              VS Codium"
  "SUPER + R            App Launcher"
  "SUPER + V            Clipboard History"
  "SUPER + SHIFT + .    Emoji Picker - GUI"
  "SUPER + .            Emoji Picker - Wofi"
  "PRINT                Screenshot Selection"
  "SUPER + ALT + K      Calculator"

  "SUPER + C            Close Window"
  "SUPER + F            Toggle Fullscreen"
  "SUPER + ALT + F      Toggle Floating"
  "SUPER + P            Toggle Pseudo (Dwindle)"
  "SUPER + J            Toggle Split (Dwindle)"
  "SUPER + L            Lock Screen"
  "SUPER + ESC          Power Menu"
  "SUPER + M            Exit Hyprland"

  "SUPER + ←            Move Focus Left"
  "SUPER + →            Move Focus Right"
  "SUPER + ↑            Move Focus Up"
  "SUPER + ↓            Move Focus Down"
  "SUPER + LMB Drag     Move Window"
  "SUPER + RMB Drag     Resize Window"
  "SUPER + H            Move Window Left"
  "SUPER + L            Move Window Right"
  "SUPER + K            Move Window Up"
  "SUPER + J            Move Window Down"
  "SUPER + LMB Drag     Move Window"
  "SUPER + RMB Drag     Resize Window"

  "SUPER + 1            Switch to Workspace 1"
  "SUPER + 2            Switch to Workspace 2"
  "SUPER + N            Switch to Workspace N"
  "SUPER + 0            Switch to Workspace 10"
  "SUPER + SHIFT + 1    Move Window to Workspace 1"
  "SUPER + SHIFT + 2    Move Window to Workspace 2"
  "SUPER + SHIFT + N    Move Window to Workspace N"
  "SUPER + SHIFT + 0    Move Window to Workspace 10"
  "SUPER + S            Toggle Special Workspace"
  "SUPER + SHIFT + S    Move Window to Special Workspace"
  "SUPER + Scroll ↓     Next Workspace"
  "SUPER + Scroll ↑     Previous Workspace"

  "Volume Up Key        Increase Volume"
  "Volume Down Key      Decrease Volume"
  "Mute Key             Toggle Output Mute"
  "Mic Mute Key         Toggle Mic Mute"
  "Brightness Up Key    Increase Brightness"
  "Brightness Down Key  Decrease Brightness"
  "Media Next           Next Track"
  "Media Play/Pause     Play / Pause"
  "Media Previous       Previous Track"
)

choice=$(printf "%s\n" "${menu_entries[@]}" |
  sed 's/│/\t/' |
  wofi --dmenu \
    --hide-scroll \
    --class wofi-keybinds \
    --columns 2 \
    --width 875 \
    --height 480 \
    --prompt "                 SUPER is the Windows key and H, J, K, L is left down up right")

exit 0
