#!/usr/bin/env bash

amethyst_void() {
  rm ~/.local/marchyso-theme/backup/*
  rm  ~/.config/waybar/*
  rm  ~/.config/swaync/*
  cp -r ~/.local/marchyso-theme/amethyst-void/waybar/* ~/.config/waybar
  cp -r ~/.local/marchyso-theme/amethyst-void/swaync/* ~/.config/swaync
  awww img ~/Pictures/Wallpapers/purple.jpg --transition-fps 60 --transition-step 255 --transition-type any
  sleep 1
  waybar-start
  pkill swaync
  swaync &
}

Cherrywave() {
  rm ~/.local/marchyso-theme/backup/*
  rm  ~/.config/waybar/*
  cp -r ~/.local/marchyso-theme/cherrywave/waybar/* ~/.config/waybar
  cp -r ~/.local/marchyso-theme/cherrywave/swaync/* ~/.config/swaync
  awww img ~/Pictures/Wallpapers/cyberpunk-1920x1080-nnly8wng1ef964p9.jpg --transition-fps 60 --transition-step 255 --transition-type any
  sleep 1
  waybar-start
  pkill swaync
  swaync &
}

Catppuchin() {
  rm ~/.local/marchyso-theme/backup/*
  rm  ~/.config/waybar/*
  rm  ~/.config/swaync/*
  cp -r ~/.local/marchyso-theme/catppuchin-machiato/waybar/* ~/.config/waybar
  cp -r ~/.local/marchyso-theme/catppuchin-machiato/swaync/* ~/.config/swaync
  awww img ~/Pictures/Wallpapers/a1c1250c87bedfe070682ded0f8019632a2bd489.jpg --transition-fps 60 --transition-step 255 --transition-type any
  sleep 1
  waybar-start
  pkill swaync
  swaync &
}

Dock() {
  rm ~/.local/marchyso-theme/backup/*
  rm  ~/.config/waybar/*
  rm  ~/.config/swaync/*
  cp -r ~/.local/marchyso-theme/dock/waybar/* ~/.config/waybar
  cp -r ~/.local/marchyso-theme/dock/swaync/* ~/.config/swaync
  awww img ~/Pictures/Wallpapers/tank.jpg --transition-fps 60 --transition-step 255 --transition-type any
  sleep 1
  waybar-start
  pkill swaync
  swaync &
}

# Ordered entries: "Label|function"
menu_entries=(
  "Amethys Void|amethyst_void"
  "Cherrywave|Cherrywave"
  "Catppuchin|Catppuchin"
  "Dock|Dock"
)

# Extract labels for display
labels=$(printf "%s\n" "${menu_entries[@]}" | cut -d'|' -f1)

choice=$(printf "%s\n" "$labels" | \
  wofi --dmenu \
     --prompt "Choose your theme" \
     --width 300 \
     --height 275)

# Execute matching function
for entry in "${menu_entries[@]}"; do
  label="${entry%%|*}"
  action="${entry##*|}"
  [[ "$choice" == "$label" ]] && "$action"
done
