#!/usr/bin/env bash

amethyst_void() {
  rm ~/.local/marchyso-theme/backup/*
  rm  ~/.config/waybar/*
  rm  ~/.config/swaync/*
  cp -r ~/.local/marchyso-theme/amethyst-void/waybar/* ~/.config/waybar
  cp -r ~/.local/marchyso-theme/amethyst-void/swaync/* ~/.config/swaync
  awww img ~/Pictures/Wallpapers/purple.jpg --transition-fps 60 --transition-step 255 --transition-type any
  sleep 1
  waybar-start
  pkill swaync
  swaync &
}

Cherrywave() {
  rm ~/.local/marchyso-theme/backup/*
  rm  ~/.config/waybar/*
  cp -r ~/.local/marchyso-theme/cherrywave/waybar/* ~/.config/waybar
  cp -r ~/.local/marchyso-theme/cherrywave/swaync/* ~/.config/swaync
  awww img ~/Pictures/Wallpapers/cyberpunk.jpg --transition-fps 60 --transition-step 255 --transition-type any
  sleep 1
  waybar-start
  pkill swaync
  swaync &
}

Catppuchin() {
  rm ~/.local/marchyso-theme/backup/*
  rm  ~/.config/waybar/*
  rm  ~/.config/swaync/*
  cp -r ~/.local/marchyso-theme/catppuchin-machiato/waybar/* ~/.config/waybar
  cp -r ~/.local/marchyso-theme/catppuchin-machiato/swaync/* ~/.config/swaync
  awww img ~/Pictures/Wallpapers/catppuchin.jpg --transition-fps 60 --transition-step 255 --transition-type any
  sleep 1
  waybar-start
  pkill swaync
  swaync &
}

Dock() {
  rm ~/.local/marchyso-theme/backup/*
  rm  ~/.config/waybar/*
  rm  ~/.config/swaync/*
  cp -r ~/.local/marchyso-theme/dock/waybar/* ~/.config/waybar
  cp -r ~/.local/marchyso-theme/dock/swaync/* ~/.config/swaync
  awww img ~/Pictures/Wallpapers/tank.jpg --transition-fps 60 --transition-step 255 --transition-type any
  sleep 1
  waybar-start
  pkill swaync
  swaync &
}

sidebar() {
  rm ~/.local/marchyso-theme/backup/*
  rm  ~/.config/waybar/*
  rm  ~/.config/swaync/*
  cp -r ~/.local/marchyso-theme/Expressive/waybar/* ~/.config/waybar
  cp -r ~/.local/marchyso-theme/Expressive/swaync/* ~/.config/swaync
  awww img ~/Pictures/Wallpapers/couple-bus-sunset.jpg --transition-fps 60 --transition-step 255 --transition-type any
  sleep 1
  waybar-start
  pkill swaync
  swaync &
}



# Ordered entries: "Label|function"
menu_entries=(
  "Amethys Void|amethyst_void"
  "Cherrywave|Cherrywave"
  "Catppuchin|Catppuchin"
  "Dock|Dock"
  "Gruvbox Dark"
  "Expressive|sidebar"
)

# Extract labels for display
labels=$(printf "%s\n" "${menu_entries[@]}" | cut -d'|' -f1)

choice=$(printf "%s\n" "$labels" | \
  wofi --dmenu \
     --prompt "Choose your theme" \
     --width 300 \
     --height 500)

# Execute matching function
for entry in "${menu_entries[@]}"; do
  label="${entry%%|*}"
  action="${entry##*|}"
  [[ "$choice" == "$label" ]] && "$action"
done
