#!/usr/bin/env bash

choice=$(printf "⏻ Shutdown\n↻ Reboot\n🗝 Lock\n⎋ Logout" | wofi --dmenu --prompt "Power")

case "$choice" in
  *Shutdown) systemctl poweroff ;;
  *Reboot)   systemctl reboot ;;
  *Lock)     hyprlock ;;
  *Logout)   hyprctl dispatch exit ;;
esac
