exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = cliphist wipe
exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data
exec-once = ~/.local/bin/waybar-start
exec-once = awww-daemon && awww restore
exec-once = xsettingsd &
exec-once = swaync
exec-once = orbit daemon &
exec-once = sh ~/.config/hypr/scripts/weather/weather.sh
exec-once = hypridle
exec-once = wl-clip-persist --clipboard both
