windowrulev = suppressevent maximize, class:.*

windowrulev = nofocus 1, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0
windowrulev = size 900 600,class:^(wofi-keybinds)$
windowrulev = blur,class:^(wofi)$
windowrulev = animation popin,class:^(wofi)$
windowrulev = float, title:^(wofi-power)$
windowrulev = size 400 250, title:^(wofi-power)$
windowrulev = move 100%-420 20, title:^(wofi-power)$

windowrulev = fullscreen 1,class:^(screensaver)$
windowrulev = noborder,class:^(screensaver)$

windowrulev = tile, class:^(War Thunder \(Vulkan, 64bit\))$
